import { PLAYER, WORLD } from '../constants'
import type {
  AuthoredWorldData,
  BuildingModuleDefinition,
  GroundModuleDefinition,
  PropModuleDefinition,
  SpawnPointDefinition,
} from './worldTypes'

function ground(definition: GroundModuleDefinition): GroundModuleDefinition {
  return definition
}

function building(definition: BuildingModuleDefinition): BuildingModuleDefinition {
  return definition
}

function prop(definition: PropModuleDefinition): PropModuleDefinition {
  return definition
}

function spawn(definition: SpawnPointDefinition): SpawnPointDefinition {
  return definition
}

/**
 * Hand-authored slice: irregular piazza + borgo alleys + eastward blocks toward the landmark.
 * Buildings use wings (L-blocks), rustication, pitched roofs, and renaissance facades where noted.
 */
export function createDistrictSlice(): AuthoredWorldData {
  return {
    primarySpawnId: 'spawn-loggia',
    modules: [
      /* --- Ground / streets (organic grid, not one big rectangle) --- */
      ground({
        kind: 'ground',
        id: 'plaza-san-lorenzo',
        label: 'San Lorenzo Plaza',
        archetype: 'plaza',
        position: { x: -33, y: WORLD.GROUND_Y, z: 26 },
        footprint: { width: 34, depth: 28 },
        material: 'plazaStone',
        tags: ['openPassage'],
        routeKind: 'ground',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'piazza-minor',
        label: 'Piazza del Mercato Nuovo',
        archetype: 'plaza',
        position: { x: 12, y: WORLD.GROUND_Y, z: 42 },
        footprint: { width: 24, depth: 20 },
        material: 'plazaStone',
        tags: ['openPassage'],
        routeKind: 'ground',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'via-mercato',
        label: 'Via Mercato',
        archetype: 'street',
        position: { x: -4, y: WORLD.GROUND_Y, z: 26 },
        footprint: { width: 58, depth: 12 },
        material: 'streetStone',
        tags: ['parkourStarter'],
        routeKind: 'ground',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'via-calzaiuoli',
        label: 'Via dei Calzaiuoli',
        archetype: 'street',
        position: { x: 2, y: WORLD.GROUND_Y, z: 34 },
        footprint: { width: 44, depth: 7 },
        material: 'streetStone',
        tags: ['parkourStarter'],
        routeKind: 'ground',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'via-rooftop',
        label: 'Via Rooftop',
        archetype: 'street',
        position: { x: -7, y: WORLD.GROUND_Y, z: 12 },
        footprint: { width: 64, depth: 8 },
        material: 'streetStone',
        tags: ['parkourStarter'],
        routeKind: 'ground',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'via-duomo-approach',
        label: 'Approach to the Duomo',
        archetype: 'street',
        position: { x: 38, y: WORLD.GROUND_Y, z: -8 },
        footprint: { width: 14, depth: 52 },
        material: 'streetStone',
        tags: ['parkourStarter'],
        routeKind: 'ground',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'borgo-a',
        label: 'Borgo San Jacopo',
        archetype: 'alley',
        position: { x: -22, y: WORLD.GROUND_Y, z: -22 },
        footprint: { width: 2.8, depth: 22 },
        material: 'streetStone',
        tags: ['wallRunnable'],
        routeKind: 'connector',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'borgo-b',
        label: 'Borgo Elbow',
        archetype: 'alley',
        position: { x: -14, y: WORLD.GROUND_Y, z: -32 },
        footprint: { width: 18, depth: 2.8 },
        material: 'streetStone',
        tags: ['wallRunnable'],
        routeKind: 'connector',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'alley-courier',
        label: 'Courier Alley',
        archetype: 'alley',
        position: { x: -17.5, y: WORLD.GROUND_Y, z: -9 },
        footprint: { width: 3, depth: 34 },
        material: 'streetStone',
        tags: ['wallRunnable'],
        routeKind: 'connector',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'alley-bell',
        label: 'Bell Alley',
        archetype: 'alley',
        position: { x: 1.5, y: WORLD.GROUND_Y, z: -9 },
        footprint: { width: 3, depth: 34 },
        material: 'streetStone',
        tags: ['wallRunnable'],
        routeKind: 'connector',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'cut-through',
        label: 'Masons Cut-Through',
        archetype: 'alley',
        position: { x: -7, y: WORLD.GROUND_Y, z: -9 },
        footprint: { width: 60, depth: 2 },
        material: 'streetStone',
        tags: ['openPassage'],
        routeKind: 'connector',
        layer: 'ground',
      }),
      ground({
        kind: 'ground',
        id: 'courtyard-sand',
        label: 'Inner Cortile',
        archetype: 'plaza',
        position: { x: 32, y: WORLD.GROUND_Y, z: 18 },
        footprint: { width: 14, depth: 12 },
        material: 'plazaStone',
        tags: ['openPassage'],
        routeKind: 'connector',
        layer: 'ground',
      }),

      /* --- Core block (upgraded silhouettes) --- */
      building({
        kind: 'building',
        id: 'residential-olive',
        label: 'Olive Roof House',
        archetype: 'residential',
        position: { x: -28, y: 0, z: -18 },
        footprint: { width: 18, depth: 16 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stucco',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['windowSills', 'drainpipe'],
      }),
      building({
        kind: 'building',
        id: 'commercial-apothecary',
        label: 'Apothecary Roof',
        archetype: 'commercial',
        position: { x: -8, y: 0, z: -18 },
        footprint: { width: 16, depth: 16 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stucco',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'parkourStarter'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['windowSills', 'awning'],
      }),
      building({
        kind: 'building',
        id: 'palazzo-medici-lite',
        label: 'Stone Palazzo Roof',
        archetype: 'palazzo',
        position: { x: 13, y: 0, z: -18 },
        footprint: { width: 20, depth: 16 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stone',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'wallRunnable'],
        wallTags: ['climbable', 'wallRunnable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'renaissance',
        roofStyle: 'flat',
        features: ['balcony', 'windowSills'],
      }),
      building({
        kind: 'building',
        id: 'residential-loggia',
        label: 'Loggia Roof House',
        archetype: 'residential',
        position: { x: -28, y: 0, z: 0 },
        footprint: { width: 18, depth: 16 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stucco',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'parkourStarter'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['balcony', 'drainpipe'],
      }),
      building({
        kind: 'building',
        id: 'commercial-loggia',
        label: 'Brick Loggia Roof',
        archetype: 'commercial',
        position: { x: -8, y: 0, z: 0 },
        footprint: { width: 16, depth: 16 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'brick',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'wallRunnable'],
        wallTags: ['climbable', 'wallRunnable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'plain',
        roofStyle: 'pitched',
        features: ['windowSills', 'awning'],
      }),
      building({
        kind: 'building',
        id: 'workshop-bell',
        label: 'Bell Workshop Roof',
        archetype: 'commercial',
        position: { x: 13, y: 0, z: 0 },
        footprint: { width: 20, depth: 16 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'brick',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'wallRunnable'],
        wallTags: ['climbable', 'wallRunnable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['windowSills', 'awning'],
      }),

      /* --- L-shaped corner palazzo + row toward east --- */
      building({
        kind: 'building',
        id: 'palazzo-corner-L',
        label: 'Palazzo dei Mercanti',
        archetype: 'palazzo',
        position: { x: 55, y: 0, z: 42 },
        footprint: { width: 16, depth: 14 },
        wings: [{ offsetX: -12, offsetZ: -8, width: 14, depth: 14 }],
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stone',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'wallRunnable'],
        wallTags: ['climbable', 'wallRunnable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'renaissance',
        roofStyle: 'pitched',
        features: ['windowSills', 'balcony'],
      }),
      building({
        kind: 'building',
        id: 'casa-stretto',
        label: 'Torre House (narrow)',
        archetype: 'residential',
        position: { x: 6, y: 0, z: 46 },
        footprint: { width: 9, depth: 18 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stucco',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['windowSills', 'drainpipe'],
      }),
      building({
        kind: 'building',
        id: 'bottega-east',
        label: 'Bottega Facade Row',
        archetype: 'commercial',
        position: { x: 22, y: 0, z: 48 },
        footprint: { width: 22, depth: 12 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stucco',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'parkourStarter'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'renaissance',
        roofStyle: 'pitched',
        features: ['awning', 'windowSills'],
      }),
      building({
        kind: 'building',
        id: 'cortile-north',
        label: 'Cortile North Wing',
        archetype: 'residential',
        position: { x: 32, y: 0, z: 28 },
        footprint: { width: 18, depth: 11 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'brick',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['windowSills'],
      }),
      building({
        kind: 'building',
        id: 'cortile-east',
        label: 'Cortile East Wing',
        archetype: 'palazzo',
        position: { x: 42, y: 0, z: 18 },
        footprint: { width: 11, depth: 16 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stone',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'wallRunnable'],
        wallTags: ['climbable', 'wallRunnable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'renaissance',
        roofStyle: 'flat',
        features: ['windowSills'],
      }),
      building({
        kind: 'building',
        id: 'cortile-south',
        label: 'Cortile South Wing',
        archetype: 'residential',
        position: { x: 32, y: 0, z: 8 },
        footprint: { width: 18, depth: 11 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stucco',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'plain',
        roofStyle: 'pitched',
        features: ['balcony'],
      }),

      /* --- East quarter toward landmark --- */
      building({
        kind: 'building',
        id: 'east-row-a',
        label: 'Ripa Row A',
        archetype: 'commercial',
        position: { x: 44, y: 0, z: 6 },
        footprint: { width: 14, depth: 20 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'brick',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'wallRunnable'],
        wallTags: ['climbable', 'wallRunnable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['windowSills'],
      }),
      building({
        kind: 'building',
        id: 'east-row-b',
        label: 'Ripa Row B',
        archetype: 'residential',
        position: { x: 44, y: 0, z: -14 },
        footprint: { width: 14, depth: 18 },
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'stucco',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'rusticated',
        roofStyle: 'pitched',
        features: ['windowSills', 'drainpipe'],
      }),
      building({
        kind: 'building',
        id: 'east-L-workshop',
        label: 'L-Shaped Workshop',
        archetype: 'commercial',
        position: { x: 30, y: 0, z: -28 },
        footprint: { width: 14, depth: 12 },
        wings: [{ offsetX: -6, offsetZ: -10, width: 16, depth: 10 }],
        height: WORLD.ROOFTOP_Y,
        wallMaterial: 'brick',
        roofMaterial: 'roofTile',
        tags: ['climbable', 'ledge', 'parkourStarter'],
        wallTags: ['climbable'],
        roofTags: ['ledge'],
        routeKind: 'rooftop',
        layer: 'rooftop',
        facadeStyle: 'plain',
        roofStyle: 'pitched',
        features: ['awning'],
      }),

      building({
        kind: 'building',
        id: 'duomo-inspired',
        label: 'Duomo-Inspired Landmark',
        archetype: 'landmark',
        position: { x: 50, y: 0, z: -34 },
        footprint: { width: 28, depth: 22 },
        height: 10,
        wallMaterial: 'stone',
        roofMaterial: 'roofTile',
        tags: ['landmark', 'wallRunnable'],
        wallTags: ['wallRunnable'],
        roofTags: ['landmark'],
        routeKind: 'landmark',
        layer: 'rooftop',
        facadeStyle: 'renaissance',
        roofStyle: 'flat',
        hasDome: true,
        hasTower: true,
      }),

      /* --- Props --- */
      prop({
        kind: 'prop',
        id: 'plaza-stall-west',
        label: 'West Market Stall',
        archetype: 'marketStall',
        position: { x: -41, y: 1.1, z: 24 },
        size: { x: 3.5, y: 2.2, z: 2.8 },
        material: 'wood',
        tags: ['vaultable', 'parkourStarter'],
        routeKind: 'ground',
        layer: 'transition',
        walkableTop: true,
      }),
      prop({
        kind: 'prop',
        id: 'plaza-stall-east',
        label: 'East Market Stall',
        archetype: 'marketStall',
        position: { x: -31, y: 1.1, z: 30 },
        size: { x: 3.5, y: 2.2, z: 2.8 },
        material: 'wood',
        tags: ['vaultable', 'parkourStarter'],
        routeKind: 'ground',
        layer: 'transition',
        walkableTop: true,
      }),
      prop({
        kind: 'prop',
        id: 'stall-mercato-nuovo',
        label: 'Mercato Nuovo Stall',
        archetype: 'marketStall',
        position: { x: 8, y: 1.1, z: 44 },
        size: { x: 3.2, y: 2, z: 2.6 },
        material: 'wood',
        tags: ['vaultable', 'parkourStarter'],
        routeKind: 'ground',
        layer: 'transition',
        walkableTop: true,
      }),
      prop({
        kind: 'prop',
        id: 'crate-corner-south',
        label: 'South Corner Crates',
        archetype: 'crateCluster',
        position: { x: -18, y: 1, z: 18 },
        size: { x: 2.8, y: 2, z: 2.8 },
        material: 'wood',
        tags: ['climbable', 'vaultable', 'parkourStarter'],
        routeKind: 'connector',
        layer: 'transition',
        walkableTop: true,
      }),
      prop({
        kind: 'prop',
        id: 'crate-corner-east',
        label: 'East Corner Crates',
        archetype: 'crateCluster',
        position: { x: 4, y: 1, z: 10 },
        size: { x: 2.6, y: 2, z: 2.6 },
        material: 'wood',
        tags: ['climbable', 'vaultable', 'parkourStarter'],
        routeKind: 'connector',
        layer: 'transition',
        walkableTop: true,
      }),
      prop({
        kind: 'prop',
        id: 'barrels-bell-alley',
        label: 'Bell Alley Barrels',
        archetype: 'barrelStack',
        position: { x: 2.5, y: 0.75, z: -1 },
        size: { x: 1.8, y: 1.5, z: 1.8 },
        material: 'wood',
        tags: ['vaultable', 'parkourStarter'],
        routeKind: 'connector',
        layer: 'transition',
      }),
      prop({
        kind: 'prop',
        id: 'courtyard-arch',
        label: 'Courtyard Arch',
        archetype: 'archway',
        position: { x: -7, y: 2.1, z: 11 },
        size: { x: 4.5, y: 4.2, z: 1.2 },
        material: 'stone',
        tags: ['openPassage'],
        routeKind: 'connector',
        layer: 'transition',
      }),
      prop({
        kind: 'prop',
        id: 'arch-cortile',
        label: 'Cortile Passage',
        archetype: 'archway',
        position: { x: 32, y: 2.1, z: 25 },
        size: { x: 3.5, y: 3.8, z: 1.1 },
        material: 'stone',
        tags: ['openPassage'],
        routeKind: 'connector',
        layer: 'transition',
      }),
    ],
    spawnPoints: [
      spawn({
        id: 'spawn-loggia',
        label: 'Loggia Roof Spawn',
        position: { x: -28, y: WORLD.ROOFTOP_Y + PLAYER.HALF_HEIGHT, z: 0 },
      }),
      spawn({
        id: 'spawn-palazzo',
        label: 'Palazzo Roof Spawn',
        position: { x: 13, y: WORLD.ROOFTOP_Y + PLAYER.HALF_HEIGHT, z: -18 },
      }),
      spawn({
        id: 'spawn-apothecary',
        label: 'Apothecary Roof Spawn',
        position: { x: -8, y: WORLD.ROOFTOP_Y + PLAYER.HALF_HEIGHT, z: -18 },
      }),
      spawn({
        id: 'spawn-mercato-nuovo',
        label: 'Mercato Nuovo Roof Spawn',
        position: { x: 22, y: WORLD.ROOFTOP_Y + PLAYER.HALF_HEIGHT, z: 48 },
      }),
      spawn({
        id: 'spawn-east-ripa',
        label: 'Ripa Row Spawn',
        position: { x: 44, y: WORLD.ROOFTOP_Y + PLAYER.HALF_HEIGHT, z: 6 },
      }),
    ],
  }
}
